### ISSUE TITLE
Request to add "priority" props for pre-loading Images

### ISSUE THREAD

**Issue by DevenRathod2** [sangeethkumarsg/next-image-gallery#1]
Request to add "priority" props for pre-loading Images and can you give me the step to add that?

**Comment by sangeethkumarsg** [comment]
Hi @DevenRathod2 ,
Support of `priority` field of Next JS has been added in [v 0.0.26](https://www.npmjs.com/package/next-image-gallery/v/0.0.26). Check the Readme.md file for more details.

You can pass `priorityLoad` true to those images which needs to pre-load. Default value is false.
